import Head from "next/head";

import Image from "next/image";
import styles from "@client/styles/Home.module.css";
import { useAppSelector } from "@client/shared/redux-hooks";
import { useGetTestQuery } from "@client/shared/slices/test-api";
import { useSession, signIn, signOut } from "next-auth/react";
import { Button, Text } from "@chakra-ui/react";

export default function Home({ data }: any) {
  const count = useAppSelector((state) => state.test);
  const { data: testResponse, isLoading } = useGetTestQuery();
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{ display: "flex", flexDirection: "column", gap: 10 }}
          className={styles.center}
        >
          <h3>ServeSSr: {data?.message}</h3>
          <h3>Dynamic: {isLoading ? "LOADING" : testResponse?.length}</h3>
          {session ? <div>logged</div> : <div>not logged</div>}
          <Button size="sm" colorScheme="primary" onClick={() => signIn()}>
            Sign in
          </Button>
          <Text fontSize="xs" color="primary.500">
            Admin
          </Text>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/post/test`);
  const response = await res.json();
  return { props: { data: response } };
};
